import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { add, getTestState } from '@features/tmpSlice';
import { AppDispatch } from '@app/store';
import { connect } from 'react-redux';

type Props = StateProps & DispatchProps;

const Home = ({ num, onAdd }: Props) => {
	const { _num } = num;
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<div>{_num}</div>
				<button onClick={() => onAdd(2)}>+</button>
			</main>

			<footer className={styles.footer}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by{' '}
					<span className={styles.logo}>
						<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>
	);
};

interface StateProps {
	num: number;
}

const mapStateToProps = (state: RootState) => ({
	num: getTestState(state),
});

interface DispatchProps {
	onAdd: (num: number | undefined) => void;
}

const mapDispatchToProps = (dispatch: AppDispatch): DispatchProps => ({
	onAdd: (num: number | undefined) => dispatch(add(num)),
});

export default connect(mapStateToProps, mapDispatchToProps)(Home);
